// flow-typed signature: ee0295e05b029814860cdafb914094c9
// flow-typed version: <<STUB>>/babel-preset-stage-flow_v^2.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-stage-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-stage-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-stage-flow/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-stage-flow/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-stage-flow/lib/index'>;
}
