// flow-typed signature: 3d200ffc73b36dd297a0ebef1418ef47
// flow-typed version: <<STUB>>/eslint-config-gemcook_v^1.0.5/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-gemcook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-gemcook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-gemcook/test/console' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-gemcook/index' {
  declare module.exports: $Exports<'eslint-config-gemcook'>;
}
declare module 'eslint-config-gemcook/index.js' {
  declare module.exports: $Exports<'eslint-config-gemcook'>;
}
declare module 'eslint-config-gemcook/test/console.js' {
  declare module.exports: $Exports<'eslint-config-gemcook/test/console'>;
}
