// flow-typed signature: 2c726548f0f66ec94874516301fc3b69
// flow-typed version: <<STUB>>/rollup-plugin-strip-banner_v^0.2.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-strip-banner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-strip-banner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-strip-banner/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-strip-banner/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-strip-banner/dist/index'>;
}
