// flow-typed signature: 645c357ae1032952c5037e478e52b80a
// flow-typed version: <<STUB>>/@dump247/storybook-state_v^1.5.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dump247/storybook-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dump247/storybook-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dump247/storybook-state/dist/index' {
  declare module.exports: any;
}

declare module '@dump247/storybook-state/dist/register' {
  declare module.exports: any;
}

declare module '@dump247/storybook-state/register' {
  declare module.exports: any;
}

declare module '@dump247/storybook-state/src/index' {
  declare module.exports: any;
}

declare module '@dump247/storybook-state/src/index.test' {
  declare module.exports: any;
}

declare module '@dump247/storybook-state/src/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dump247/storybook-state/dist/index.js' {
  declare module.exports: $Exports<'@dump247/storybook-state/dist/index'>;
}
declare module '@dump247/storybook-state/dist/register.js' {
  declare module.exports: $Exports<'@dump247/storybook-state/dist/register'>;
}
declare module '@dump247/storybook-state/register.js' {
  declare module.exports: $Exports<'@dump247/storybook-state/register'>;
}
declare module '@dump247/storybook-state/src/index.js' {
  declare module.exports: $Exports<'@dump247/storybook-state/src/index'>;
}
declare module '@dump247/storybook-state/src/index.test.js' {
  declare module.exports: $Exports<'@dump247/storybook-state/src/index.test'>;
}
declare module '@dump247/storybook-state/src/register.js' {
  declare module.exports: $Exports<'@dump247/storybook-state/src/register'>;
}
